### ISSUE TITLE
29 March 2023 - Emerging Technologies Initial Exploratory Meeting

### ISSUE THREAD

**Issue by psmulovics** [finos-labs/emerging-technologies#1]
## Date
29 March 2023 - 10 am EST / 3 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Presenting SIG draft charta @tenatzen 
- [x] Acceptance / reviewing of charta
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom Details

FINOS is inviting you to a scheduled Zoom meeting.

Topic: Emerging Technology SIG Proposal
Time: Mar 29, 2023 10:00 AM Eastern Time (US and Canada)

Join Zoom Meeting

https://zoom.us/j/99367109121?pwd=S0h3a3k1TjVGY1Z4cEYzamE2UWttUT09
Meeting ID: 993 6710 9121
Passcode: 357656
Dial by your location: https://zoom.us/u/azzcmrRQe

**Comment by maoo** [comment]
Maurizio Pillitu - FINOS 👋

**Comment by fxHouard** [comment]
Hello!

**Comment by mmani99** [comment]
Mani Pillai - otcDigital

**Comment by padraignix** [comment]
Patrick Downing / Morgan Stanley

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by gprs1809** [comment]
Hello! :)

**Comment by jamilmina1** [comment]
Jamil Mina / Red Hat

**Comment by ronaldssebalamu** [comment]
Ronald Ssebalamu / FINOS

**Comment by duncanjw** [comment]
Duncan Johnston-Watt | BTP

**Comment by the-schwartz** [comment]
Adam Schwartz / Synechron Consulting

**Comment by alvin-c-shih** [comment]
Alvin Shih / Morgan Stanley

**Comment by sidmocodes** [comment]
Siddharth Mohanty - Credit Suisse

**Comment by awaiken** [comment]
awaiken andrew aitken Wipro

**Comment by ditomike** [comment]
Mike Wilson, Zngly

**Comment by sonkar18** [comment]
Hello !

**Comment by bcrestel** [comment]
Ben Crestel, Morgan Stanley

**Comment by laylawhite82** [comment]
Layla White- TechPassport

**Comment by jaycangel** [comment]
Jason Engelbrecht, Citi

**Comment by brooklynrob** [comment]
Rob Underwood / Independent.

**Comment by iamrkv** [comment]
Rajesh Kumar/Independent focused on readiness (and standards) aspect of Passporting. Thank you so much for this initiative.

**Comment by psmulovics** [comment]
Hey everyone,

Thank you for the 40 people who joined yesterday for the Emerging Technologies SIG (Zenith) Proposal Meeting! There were so many amazing people who joined and so many good questions being asked!

As FINOS policies does not allow sharing the recording of the meeting, we pre-recorded our presentation, that I am happy to share here:

[![Zenith SIG - Presentation Recording](https://img.youtube.com/vi/lO-TRAQA8GE/0.jpg)](https://www.youtube.com/watch?v=lO-TRAQA8GE)

https://www.youtube.com/watch?v=lO-TRAQA8GE

As we are preparing for the board meeting end of April where we would officially present it and ask for approval, the opportunity to show interest (based on watching the recording) is still wide open – by commenting on finos/community#226  , or letting us know in email, your interest.

Thank you everyone once again who joined and who expressed interest – (hopefully) see you after the board meeting :)

Thanks,
Zenith proposed SIG group co chairs ( @psmulovics  (Morgan Stanley), @tenatzen  (Feynic), @padraignix  (Morgan Stanley))

**Comment by psmulovics** [comment]
I am happy to announce that the SIG has been accepted and ratified by the FINOS board - https://github.com/finos/community/issues/226#issuecomment-1524240180 , we are working on creating our website, mailgroup and other administrative items now.

**Comment by psmulovics** [comment]
The SIG is now live - while we do prepare our website ( https://zenith.finos.org/ coming soon ), you can already start joining the mailing lists via dropping an empty email to [zenith+subscribe@finos.org](mailto:zenith+subscribe@finos.org) !

@fxHouard, @mmani99, @vbandi, @gprs1809, @jamilmina1, @blazingpotsie, @ronaldssebalamu, @duncanjw, @the-schwartz, @alvin-c-shih, @csillazs, @sidmocodes, @awaiken, @ditomike, @sonkar18, @bcrestel, @laylawhite82, @jaycangel, @jstclair2019, @brooklynrob, @iamrkv

**Comment by jstclair2019** [comment]
@psmulovics for some reason the subcribe email got kicked back (“does not exit”)

**Comment by psmulovics** [comment]
> @psmulovics for some reason the subcribe email got kicked back (“does not exist”)

Fixed the typo 🤦

**Comment by jstclair2019** [comment]
> > @psmulovics for some reason the subcribe email got kicked back (“does not exist”)
> 
> Fixed the typo 🤦

LFG!
